default:
	@echo "#f =" $(guile #f)
	@echo "#t =" $(guile #t)
	@echo "1.8e1 =" $(guile 1.8e1)
	@echo "#\\A =" $(guile #\A)
	@echo "\"str\" =" $(guile "str")
	@echo "'sym =" $(guile 'sym)
	@echo "'(l (i s) t) =" $(guile '(l (i s) t))
